require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.4
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
